title: CppTested
locale: pl
email: tadek.biela@gmail.com
description: >-
  Blog o TDD, unit testach, nowoczesnym C++ i wielowątkowości. Jak pisać lepszy, bezpieczniejszy i bardziej przewidywalny kod.
url: https://cpptested.com
github_username: TadekBiela
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Warsaw

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Tadeusz Biela"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Jestem programistą C++ z&nbsp;wieloletnim doświadczeniem i&nbsp;pasją do&nbsp;jakościowego kodu. Na&nbsp;blogu dzielę się wiedzą o&nbsp;C++, TDD, testach jednostkowych, refaktoryzacji i&nbsp;wielowątkowości."
  links:
    - label: "E-mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:tadek.biela@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tadeuszbiela/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TadekBiela"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tadeuszbiela/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TadekBiela"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      read_time: true
      show_date: true
      related: true
      share: true
      toc: true
      sitemap: true
  # _pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
      sitemap: false

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

social:
  type: Person
  name: "Tadeusz Biela"
  links:
    - "https://www.linkedin.com/in/tadeuszbiela/"
    - "https://github.com/TadekBiela"

google_analytics: G-HKF97SJC9Z

comments:
  provider: "giscus"
  giscus:
    repo: "TadekBiela/cpptested"
    repo_id: "R_kgDOPEW3uQ"
    category: "Announcements"
    category_id: "DIC_kwDOPEW3uc4CsbpH"
    mapping: "pathname"
    strict: "0"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "top"
    theme: "light"
    lang: "pl"
    loading: "lazy"

